### ISSUE TITLE
No table "" exit

### ISSUE THREAD

**Issue by elanjcoop** [JonathanVusich/litedb#23]
![Screenshot 2020-10-28 192419](https://user-images.githubusercontent.com/71735710/97507272-352c2e80-1953-11eb-98dc-ee5fd107c8ac.png)
![Screenshot 2020-10-28 192327](https://user-images.githubusercontent.com/71735710/97507274-352c2e80-1953-11eb-842f-bbcad88aad5e.png)

**Comment by JonathanVusich** [comment]
I'm a little confused by what you have posted. You need to insert some instances of `RoundDetails` into your database before you can do any queries. Otherwise, there will be no corresponding table in the database. 

Also, I'm not sure what LiteDB Studio is, but it is totally unrelated to this python package. :)

**Comment by JonathanVusich** [comment]
Since it looks like this card is based on either incorrect usage or a misunderstanding of this package, I am going to close this card.
